repository_type: pipeline
lint:
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - assets/multiqc_config.yaml
    - assets/nf-core-sarek_logo_light.png
    - docs/images/nf-core-sarek_logo_dark.png
    - docs/images/nf-core-sarek_logo_light.png
    - lib/NfcoreTemplate.groovy
