name: NCBench Zenodo Upload
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.

on:
  # upload can only be triggered manually for now
  workflow_dispatch:
    inputs:
      germline_wes:
        description: "Trigger NCBench upload"
        type: boolean
        default: true
  pull_request:

jobs:
  ncbench-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: germline_wes
            enabled: ${{ ( github.repository == 'nf-core/sarek' ) && ( github.event_name != 'workflow_dispatch' || inputs.germline_wes ) }}
    env:
      pipeline_version: 3.2.3

    steps:
      - name: Download files from AWS
        uses: keithweaver/aws-s3-github-action@v1.0.0
        if: ${{ matrix.enabled }}
        with:
          source: s3://nf-core-awsmegatests/sarek/results-test-59026dc07633edb83aab3bfb2f65f79db38437a1/test_full/variant_calling/strelka
          command: sync
          aws_region: eu-west-1
          destination: ./variant_calling
          flags: --no-sign-request --include ".vcf.gz" --exclude "g.vcf.gz"

      - name: Download metadata file for Zenodo
        uses: actions/checkout@v4
        with:
          repository: FriederikeHanssen/sarek
          ref: ncbench
          path: sarek-ncbench/

      #- name: Create new Zenodo entry
      #  uses: popperized/zenodo/create@master
      #  env:
      #    ZENODO_METADATA_PATH: sarek-ncbench/assets/zenodo_ncbench.json
      #    ZENODO_USE_SANDBOX: true
      #  with:
      #    secrets: ${{ secrets.ZENODO_API_TOKEN }}

      #- name: Upload file to Zenodo
      #  uses: popperized/zenodo/upload@master
      #  env:
      #    ZENODO_DEPOSIT_ID:  #TODO get the dposit ID from the previous step
      #    ZENODO_UPLOAD_PATH: ./variant_calling_v$pipeline_version
      #    ZENODO_USE_SANDBOX: true
      #  with:
      #    secrets: ${{ secrets.ZENODO_API_TOKEN }}
      - name: NCBench set config
        uses: actions/checkout@v4
        with:
          repository: FriederikeHanssen/ncbench-workflow
          path: ncbench-workflow/
          ref: main
      - name: Add entry to config
        uses: mikefarah/yq@master
        with:
          cmd: yq --inplace '
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.labels;
            .site = "nf-core" |
            .pipeline = "nf-core/sarek v3.2.1" |
            .trimming = "FastP v0.23.2" |
            .read-mapping = "bwa mem v0.7.17" |
            .base-quality-recalibration = "gatk4 v4.4.0.0" |
            .realignment = "none" |
            .variant-detection  = "strelka2 v2.9.10" |
            .genotyping = "none" |
            .reads = "75M" ) |
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.subcategory;
            . = "NA12878-agilent" ) |
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.zenodo;
            .deposition = "get here proper zenodo ID"  |
            .filename = "get here proper file names" ) |
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.benchmark;
            . = "giab-NA12878-agilent-75M" ) |
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.rename-contigs;
            . = "resources/rename-contigs/ucsc-to-ensembl.txt" )
            ' ncbench-workflow/configs/config.yaml
