name: NCBench Zenodo Upload
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.

on:
  # upload can only be triggered manually for now
  workflow_dispatch:
    inputs:
      germline_wes:
        description: "Trigger NCBench upload"
        type: boolean
        default: true
  pull_request:

jobs:
  ncbench-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: germline_wes
            enabled: ${{ ( github.repository == 'nf-core/sarek' ) && ( github.event_name != 'workflow_dispatch' || inputs.germline_wes ) }}
    env:
      pipeline_version: 3.2.3

    steps:
      - name: Download files from AWS
        uses: keithweaver/aws-s3-github-action@v1.0.0
        if: ${{ matrix.enabled }}
        with:
          source: s3://nf-core-awsmegatests/sarek/results-test-59026dc07633edb83aab3bfb2f65f79db38437a1/test_full/variant_calling/strelka
          command: sync
          aws_region: eu-west-1
          destination: ./variant_calling
          flags: --no-sign-request --include ".vcf.gz" --exclude "g.vcf.gz"

      - name: Download metadata file for Zenodo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            assets/zenodo_ncbench.json
          sparse-checkout-cone-mode: false
