name: NCBench Zenodo Upload
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.

on:
  # upload can only be triggered manually for now
  workflow_dispatch:
    inputs:
      # TODO: add in other test profiles
      germline_wes:
        description: "Trigger NCBench upload"
        type: boolean
        default: true
  pull_request: # TODO: remove once it works

jobs:
  ncbench-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO: Add in other test profiles
          - profile: germline_wes
            enabled: ${{ ( github.repository == 'nf-core/sarek' ) && ( github.event_name != 'workflow_dispatch' || inputs.germline_wes ) }}
    env:
      # TODO: parse this out somehow
      pipeline_version: 3.1.1test

    steps:
      - name: Download pipeline
        uses: actions/checkout@v4

      - name: Download files from AWS
        uses: keithweaver/aws-s3-github-action@v1.0.0
        if: ${{ matrix.enabled }}
        with:
          # TODO: download all vcfs
          source: s3://nf-core-awsmegatests/sarek/results-test-59026dc07633edb83aab3bfb2f65f79db38437a1/test_full/variant_calling/strelka
          command: sync
          aws_region: eu-west-1
          destination: ./variant_calling
          flags: --no-sign-request --include ".vcf.gz" --exclude "g.vcf.gz"

      # TODO remove this, it is probably not needed anymore, we are using python now
      #- name: Create new Zenodo entry
      #  uses: popperized/zenodo/create@master
      #  env:
      #    ZENODO_METADATA_PATH: sarek-ncbench/assets/zenodo_ncbench.json
      #  entrypoint:
      #    secrets: ${{ secrets.ZENODO_DEPOSIT }}
      #
      #- name: Upload file to Zenodo
      #  uses: popperized/zenodo/upload@master
      #  env:
      #    ZENODO_UPLOAD_PATH: ./variant_calling

      - name: Install requests
        run: pip install requests # version pinning?

      - name: Upload to zenodo
        env:
          ACCESS_TOKEN: ${{ secrets.ZENODO_DEPOSIT }}
        run: |
          python .github/workflows/upload.py

      # update ncbench config yml
      - name: NCBench set config
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.NCBENCH_CI_TOKEN }}
          repository: FriederikeHanssen/ncbench-workflow
          path: ncbench-workflow/
          ref: main

      - name: Add entry to config
        uses: mikefarah/yq@master
        with:
          # TODO: add in values for all callers, ensure proper extension for the datasets are used. Parse out tool versions somehow
          # TODO: need to retrieve new zenodo id
          cmd: yq --inplace '
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.labels;
            .site = "nf-core" |
            .pipeline = "nf-core/sarek v3.2.1" |
            .trimming = "FastP v0.23.2" |
            .read-mapping = "bwa mem v0.7.17" |
            .base-quality-recalibration = "gatk4 v4.4.0.0" |
            .realignment = "none" |
            .variant-detection  = "strelka2 v2.9.10" |
            .genotyping = "none" |
            .reads = "75M" ) |
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.subcategory;
            . = "NA12878-agilent" ) |
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.zenodo;
            .deposition = $DEPOSITION_ID  |
            .filename = "get here proper file names" ) |
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.benchmark;
            . = "giab-NA12878-agilent-75M" ) |
            with(.variant-calls.nf-core-sarek-321-strelka-agilent-75M.rename-contigs;
            . = "resources/rename-contigs/ucsc-to-ensembl.txt" )
            ' ncbench-workflow/config/config.yaml

      # TODO: enable using secrets here
      - name: Commit files
        run: |
          cd ncbench-workflow
          git config --global user.email "friederike.hanssen@qbic.uni-tuebingen.de"
          git config --global user.name "FriederikeHanssen"
          git checkout -b test7
          git add config/config.yaml
          git commit -a -m "Add changes"
          git push origin test7
